### ISSUE TITLE
UI-Erstellung

### ISSUE THREAD

**Issue by Soomle** [Soomle/Analyse-digitalisierter-Fundmuenzen#12]
Implementierung der verschiedenen User-Optionen

**Comment by Shiming6612** [comment]
![UI](https://github.com/Soomle/Analyse-digitalisierter-Fundmuenzen/assets/82945561/c3cb9b31-531b-4dcc-8525-31916fc1abc3)

**Comment by Shiming6612** [comment]
Main Window Layout

- Title Bar: Displays the application name "CoinVision: Coin Image Classifier & Trainer."
- Menu Bar: Contains two main menus:
  - File Menu: Offers options for "Save as HTML" and "Exit."
  - Help Menu: Provides access to "Usage Instructions" and "About."

- Toolbar: Consists of the following buttons and controls:
  - Upload ZIP for Training: A button to select and upload a ZIP file containing training images.
  - Enable Data Augmentation Checkbox: A checkbox to toggle data augmentation on or off.
  - Augmentation Count Spinbox: A spinbox to set the number of data augmentations, enabled when data augmentation is active.
  - Upload Models: A button to upload model files.
  - Upload Image for Classification: A button to select and upload images for classification.

- Progress Bar: Visually represents the progress of current operations.
- Result Display Area: A text area for presenting the outcomes of image classifications and other messages.

Style and Design

- Fonts and Colors: The application uses the Arial font with a primary color scheme of dark teal, providing a professional appearance. Buttons change to a lighter blue upon hover.
- Buttons: All buttons have rounded corners and a dark border for better visual appeal.
- Text Area: The result display area uses the Consolas font on a light blue background for improved readability.

Interactivity

- Right-Click Menu: In the result display area, users can access functions such as "Copy," "Select All," and "Clear All" through a context menu that appears when right-clicking.
- Status Updates: The application keeps users informed of the status and progress of operations through status messages in the text area.
