### ISSUE TITLE
Test-Durchfuehrungen

### ISSUE THREAD

**Issue by Soomle** [Soomle/Analyse-digitalisierter-Fundmuenzen#13]
Ausführung von Tests mit verschiedenen Datensätzen: Präzision der Algorithmen garantieren

**Comment by Ther3000** [comment]
The "ImageDetector.exe" program is an image detection application that allows users to upload multiple models and an image to classify the image using the uploaded models. Users can interact with a graphical interface to upload models and the image, and then view the classification results from each model.

**Comment by Shiming6612** [comment]
The "ModelGeneration.exe" program generates a model from a set of images by allowing users to upload a ZIP file containing images. The program extracts features from the images, trains a OneClassSVM model with these features, and then saves the model to a specified location. Users can use a graphical interface to upload the ZIP file and select where to save the model.
